version: "3.8"

services:
  db:
    image: postgres:15
    restart: always
    container_name: url_shortener_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: url_shortner
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5
    volumes:
      - pg_data:/var/lib/postgresql/data

  # Backend Service
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: url_shortener_backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgres://postgres:12345@db:5432/url_shortner
      - PORT=3000
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    restart: always

volumes:
  pg_data:
