name: CI/CD Pipeline

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main   

jobs:

  ci:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2  

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' 

      - name: Install dependencies
        run: npm install   

      - name: Run tests
        run: npm test        

      - name: Build Docker image
        run: docker build -t your-image-name . 

  # # Job 2: Deploy to Staging (Continuous Delivery) 
  # deploy-staging:
  #   runs-on: ubuntu-latest
  #   needs: ci  # This job depends on the completion of the 'ci' job
    
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2
      
  #     - name: Set up Docker
  #       run: |
  #         docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}  # If deploying to DockerHub

  #     - name: Deploy to Staging
  #       run: |
  #         # Deploy Docker container to your staging server (e.g., AWS/GCP/Heroku)
  #         docker tag your-image-name your-dockerhub-username/your-image-name:latest
  #         docker push your-dockerhub-username/your-image-name:latest

  # # Job 3: Deploy to Production (Continuous Deployment)
  # deploy-production:
  #   runs-on: ubuntu-latest
  #   needs: deploy-staging  # This job depends on staging deployment completion
  #   if: github.ref == 'refs/heads/main'  # Run only on the 'main' branch
    
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2
      
  #     - name: Set up Docker
  #       run: |
  #         docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}  # Docker login (for DockerHub)

  #     - name: Deploy to Production
  #       run: |
  #         # Deploy Docker container to production (AWS/GCP/Heroku, etc.)
  #         docker tag your-image-name your-dockerhub-username/your-image-name:prod
  #         docker push your-dockerhub-username/your-image-name:prod
  #         # Add commands for your cloud deployment here (AWS, GCP, etc.)
